name: Packer-Backend
on:
  push:
    branches:
      - main
    paths:
      - 'src/packer/backend/**'
      - 'src/dotnet/backend/**'
env:
  DOTNET_VERSION: '6.0.401'
  PACKER_VERSION: '1.9.4'
  WORKING_DIRECTORY: "./src/packer/backend"
  DOTNET_WORKING_DIRECTORY: "./src/dotnet/backend/FleetAPI"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{ env.DOTNET_WORKING_DIRECTORY }}
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{ env.DOTNET_WORKING_DIRECTORY }}
      - name: Publish
        run: dotnet publish ./FleetAPI.csproj -c Release -o ./publish
        working-directory: ${{ env.DOTNET_WORKING_DIRECTORY }}
      - name: Generate the Deployment Package
        run: |
          cd publish
          zip -r ../deployment.zip .
        working-directory: ${{ env.DOTNET_WORKING_DIRECTORY }}
      - name: Verify Deployment Package
        run: |
          ls -lh deployment.zip
          echo "Deployment package size: $(du -h deployment.zip | cut -f1)"
        working-directory: ${{ env.DOTNET_WORKING_DIRECTORY }}
      - name: Upload Deployment Package
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-deployment
          path: ${{ env.DOTNET_WORKING_DIRECTORY }}/deployment.zip
      - name: Verify Artifact Upload
        run: |
          echo "Verifying artifact upload:"
          artifacts=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts")
          echo "$artifacts" | jq '.'
          if echo "$artifacts" | jq -e '.artifacts[] | select(.name == "dotnet-deployment")' > /dev/null; then
            echo "Artifact 'dotnet-deployment' found and uploaded successfully."
          else
            echo "Error: Artifact 'dotnet-deployment' not found!"
            exit 1
          fi

  packer:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-deployment
          path: ./deployment-package
      - name: Verify Downloaded Artifact
        run: |
          ls -lh ./deployment-package
          if [ -f "./deployment-package/deployment.zip" ]; then
            echo "Deployment package found:"
            echo "Size: $(du -h ./deployment-package/deployment.zip | cut -f1)"
          else
            echo "Error: deployment.zip not found in the downloaded artifact!"
            exit 1
          fi
      - name: Copy Deployment Package
        run: |
          cp ./deployment-package/deployment.zip ${{ env.WORKING_DIRECTORY }}/deployment.zip
      - name: Verify Copied Deployment Package
        run: |
          ls -lh ${{ env.WORKING_DIRECTORY }}/deployment.zip
          echo "Copied deployment package size: $(du -h ${{ env.WORKING_DIRECTORY }}/deployment.zip | cut -f1)"
      - id: image-version
        name: Generate Version Number
        run: |
          echo "version=$(date +'%Y.%m').${{ github.run_number }}" >> "$GITHUB_OUTPUT"
      - id: agent-ipaddress
        name: Get Agent IP Address
        run: |
          ipaddress=$(curl -s http://checkip.amazonaws.com)
          echo "ipaddress=$ipaddress" >> "$GITHUB_OUTPUT"
      - id: setup
        name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}
      - id: build
        name: Packer Build
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PKR_VAR_image_version: ${{ steps.image-version.outputs.version }}
          PKR_VAR_agent_ipaddress: ${{ steps.agent-ipaddress.outputs.ipaddress }}
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          packer init ./
          packer build -var-file=variables.pkrvars.hcl ./